[package]
name = "Flex"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.34.0"
curl = "0.4.42"
directories = "4.0.1"
infer = "0.5.0"
serde_json = "1.0.73"
url = "2.2.2"
